name: Build

# Run when tags are pushed or manually
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

# contents: write is required to publish artifacts,
# packages: write is required to push container images.
# https://goreleaser.com/ci/actions/#token-permissions
permissions:
  contents: write
  packages: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.25.x'

      - name: Go lint
        run: |
          go install golang.org/x/lint/golint@latest
          golint .

      - name: Staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

